version: '3'
services:
 minio1:
  image: minio/minio:RELEASE.2018-11-06T01-01-02Z
  volumes:
   - data1:/data
  ports:
   - "9001:9000"
  environment:
   MINIO_ACCESS_KEY: minio
   MINIO_SECRET_KEY: minio123
  command: server /data  

volumes:
  data1:
